# Generated by Django 3.1.1 on 2020-09-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200927_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_to_complete_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
