# Generated by Django 3.1.1 on 2020-09-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200927_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_to_complete_by',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
